# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('precio_liquido', models.IntegerField()),
                ('pub_modified', models.DateTimeField(verbose_name='date modified')),
                ('inv_inicial', models.IntegerField()),
                ('total_galones', models.IntegerField()),
                ('inv_final', models.IntegerField()),
                ('consumo_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidosutilitario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_liquido', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('precio_liquido', models.IntegerField()),
                ('pub_modified', models.DateTimeField(verbose_name='date modified')),
                ('inventario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('tipo_operacion', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=3)),
                ('pub_modified', models.DateTimeField(verbose_name='date modified')),
                ('porcentaje_dedicado', models.IntegerField()),
                ('horometro_inicial', models.IntegerField()),
                ('horometro_final', models.IntegerField()),
                ('operacion_id', models.IntegerField()),
                ('nombre_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_operador', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='operacion',
            name='nombre_operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Operador'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='nombre_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Equipo'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='nombre_liquido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Liquidosutilitario'),
        ),
    ]
