# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='consumo_id',
        ),
        migrations.AlterField(
            model_name='consumo',
            name='pub_modified',
            field=models.DateField(verbose_name='date modified'),
        ),
    ]
