# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170123_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnticiposRegado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('pub_modified', models.DateTimeField(verbose_name='date modified')),
                ('tipo_operacion', models.CharField(choices=[('An', 'Anticipo'), ('Re', 'Regado')], max_length=2)),
                ('cantidad', models.IntegerField()),
                ('nombre_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Compramateriales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('pub_modified', models.DateTimeField(verbose_name='date modified')),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Concepto_Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('pub_modified', models.DateField(verbose_name='date modified')),
                ('numero_factura', models.IntegerField()),
                ('peso_entrada_1', models.IntegerField()),
                ('peso_entrada_2', models.IntegerField()),
                ('peso_entrada_3', models.IntegerField()),
                ('peso_salida_1', models.IntegerField()),
                ('peso_salida_2', models.IntegerField()),
                ('peso_salida_3', models.IntegerField()),
                ('nombre_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente')),
                ('nombre_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='GastosVarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('pub_modified', models.DateField(verbose_name='date modified')),
                ('total', models.IntegerField()),
                ('concepto_gastos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Concepto_Gastos')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('precio_liquido', models.IntegerField()),
                ('pub_modified', models.DateField(verbose_name='date modified')),
                ('inv_inicial', models.IntegerField()),
                ('total_galones', models.IntegerField()),
                ('inv_final', models.IntegerField()),
                ('nombre_liquido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Liquidosutilitario')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Mina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mina', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Planta_Acopio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_planta', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Viajes_internos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('pub_modified', models.DateField(verbose_name='date modified')),
                ('cantidad', models.IntegerField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Planta_Acopio')),
                ('mina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Mina')),
                ('nombre_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Equipo')),
            ],
        ),
        migrations.AlterField(
            model_name='operacion',
            name='porcentaje_dedicado',
            field=models.IntegerField(validators=[polls.models.validate_percentage]),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='tipo_operacion',
            field=models.CharField(choices=[('D', 'Dragado'), ('E', 'Explotacion'), ('R', 'Recuperacion')], max_length=3),
        ),
        migrations.AddField(
            model_name='despacho',
            name='nombre_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Material'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='planta_Acopio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Planta_Acopio'),
        ),
        migrations.AddField(
            model_name='compramateriales',
            name='nombre_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Material'),
        ),
    ]
